apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongo-root-username: dXNlcm5hbWU= # # echo -n 'username' | base64
  mongo-root-password: cGFzc3dvcmQ= # # echo -n 'password' | base64