apiVersion: apps/v1
kind: Deployment
metadata:
  name: cnn-client
  labels:
    app: cnn-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cnn-client
  template:
    metadata:
      labels:
        app: cnn-client
    spec:
      containers:
      - name: cnn-client
        image: pjt3591oo/cnn-client-tutorial:0.2
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        # command: ["uvicorn", "server:app", "--host", "0.0.0.0", "--port", "80"]
---
apiVersion: v1
kind: Service
metadata:
  name: cnn-client-service
spec:
  ports:
    - port: 4200
      targetPort: 80
      nodePort: 32100
  selector:
    app: cnn-client
  type: NodePort